# -*- coding: utf-8 -*-
"""White_box_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Jzgqd4dAbR4iyHGnjWSFnkZvAWtr9zr
"""

from google.colab import drive
drive.mount("/content/drive")

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
sns.set(style="white", color_codes=True)

iris = pd.read_csv("/content/drive/MyDrive/dataset/Iris.csv") # Corrected file path
iris.head()

iris ["Species"].value_counts()

"""scatter plot"""

sns.FacetGrid(iris, hue="Species", height=6).map(plt.scatter, "PetalLengthCm", "SepalWidthCm").add_legend()

flower_mapping = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica':2}
iris["Species"] = iris["Species"].map(flower_mapping)

iris. head()

X=iris[[ 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values
Y=iris[['Species']].values

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,Y)

model.score(X,Y)

expected = Y
predicted = model.predict(X)
predicted

from sklearn import metrics
print (metrics.classification_report (expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

print (metrics.confusion_matrix(expected, predicted))